spring.application.name=airBnBClone

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb_clone
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


#Server Configuration

# below property is used to set the context path for the application,
# which means all endpoints will be prefixed with /api/v1
server.servlet.context-path=/api/v1

#JWT Configuration
jwt.secret.key=9f3c7a4e2b1d8c6f5a9e0d3b7c4f1a2e8d6c5b9a3f7e1d2c4a8b6e9f0d3c7a1b8e6f2c5d9a4b7e3c1f8d0a6b5c2e9f7